// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[] = SECRET_DEVICE_LOGIN_NAME;

const char SSID[] = SECRET_SSID;             // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = SECRET_DEVICE_KEY; // Secret device password

void onWarningChange();

String warning;
float pressure;
CloudTemperatureSensor temperatureIn;
CloudTemperatureSensor temperatureOut;
CloudTemperatureSensor temperaturePool;

void initProperties()
{
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(warning, READWRITE, ON_CHANGE, onWarningChange);
  ArduinoCloud.addProperty(pressure, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatureIn, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatureOut, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperaturePool, READ, 1 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
